### ISSUE TITLE
docker-options:add from remote set first argument only

### ISSUE THREAD

**Issue by znz** [progrium/dokku#1135]
I expected to set `-v /example` but `-v` only when `docker-options:add` via ssh.

```
% ssh dokku docker-options:add node-js-app build,deploy,run "-v /example"
Connection to 10.0.0.2 closed.
% ssh dokku docker-options node-js-app
Build options:
    -v
Deploy options:
    -v
Run options:
    -v
Connection to 10.0.0.2 closed.
```
Running `docker-options:add` on dokku host is expected behavior.

```
vagrant@dokku:~$ sudo dokku docker-options:add node-js-app build,deploy,run "-v /example"
vagrant@dokku:~$ sudo dokku docker-options node-js-app
Build options:
    -v /example
Deploy options:
    -v /example
Run options:
    -v /example
```

**Comment by michaelshobbs** [comment]
Should be fixed by #1145

**Comment by vincentfretin** [comment]
Hi @michaelshobbs Your fix is not enough apparently, I still have issues, see
https://github.com/progrium/dokku/issues/1187
