### ISSUE TITLE
Unfinished pushing Ruby app. Docker/buildpack/herokuish issue?

### ISSUE THREAD

**Issue by pearlymaccha** [progrium/dokku#1318]
Hello, I was trying to push a Ruby app but I got an unfinished process. Please see this: https://gist.github.com/pearlymaccha/16771c739fbd993ae3d9
I've done 'git pull origin master' on Herokuish, but I don't know how to update it. When I check my Herokuish version, it's still v0.3.0. I need the Herokuish v0.3.1.

The last line of the process is:
<code>-----> Adding BUILD_ENV to build environment...</code>
<code>-----> Fetching custom buildpack</code>

I think it's related to docker or buildpack or herokuish. Can someone tell me how to fix this?

**Comment by michaelshobbs** [comment]
@josegonzalez have we fixed the buildstep release yet and updated it to herokish 0.3.1?

**Comment by pearlymaccha** [comment]
Yes, I've successfully updated herokuish to v0.3.1. But I still get the message above. When I check my herokuish version, the result is:

herokuish: 0.3.1
buildpacks:
heroku-buildpack-clojure v63
heroku-buildpack-go b261aab
heroku-buildpack-gradle v12
heroku-buildpack-grails 1ef927d
heroku-buildpack-java v33
heroku-buildpack-multi cddec34
heroku-buildpack-nodejs v76
heroku-buildpack-php v57
heroku-buildpack-play v23
heroku-buildpack-python v53
heroku-buildpack-ruby v129
heroku-buildpack-scala v58

How to get heroku-buildpack-ruby v138 (latest)?

**Comment by michaelshobbs** [comment]
I assume you ran that herokuish command inside a buildstep or app container, ya?

To use the latest or any buildpack not included in the image, set the BUILDPACK_URL environment variable to the GitHub url of the desired buildpack. Look for "custom buildpack" in the documentation. I think it's under application deployment.

**Comment by pearlymaccha** [comment]
Yes, I ran it inside docker. I've set the 'dokku config:set devss BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-ruby.git#138'. But maybe I forget to add the .env file. I'll try it tomorrow :)

**Comment by michaelshobbs** [comment]
That should be enough. You won't see the version change when you run herokuish buildpacks as the build system downloads the version you specified on deploy.

**Comment by pearlymaccha** [comment]
I still can't push Ruby app to Dokku :(

**Comment by michaelshobbs** [comment]
It would seem then your issue is not the herokuish/buildpack version problem. It doesn't seem like it's not able to download the buildpack. So a networking issue? I've seen folks have issues when IPv6 is enabled on platforms like DigitalOcean. I've also seen folks have slow networks and setting `CURL_TIMEOUT` and `CURL_CONNECT_TIMEOUT` to high values sometimes helps.

**Comment by michaelshobbs** [comment]
@pearlymaccha any success here? there is a new buildstep release. maybe try that?

**Comment by pearlymaccha** [comment]
I haven't try new buildstep, I'll try it later :)

**Comment by pearlymaccha** [comment]
Can I update new buildstep by doing 'git pull origin master' from github.com/progrium/buildstep? Or is there another way to update buildstep? Thank you :)
*note: I've done the README.md

**Comment by michaelshobbs** [comment]
Steps to rebuild buildstep
- pull master from progrium/dokku
- destroy all dokku apps
- run `BUILD_STACK=true make -e stack`
- redeploy your apps
- profit!!! :smile:

**Comment by pearlymaccha** [comment]
I've done it all :) But still, couldn't push Ruby app. But now, I couldn't push another app, like Node.js and Java apps. Is anyone success pushing app after updating Dokku to v 0.3.22?

**Comment by michaelshobbs** [comment]
This issue is almost certainly not a bug in dokku. You'll need to dig in further with regards to your environment. Perhaps attempt deploying in a different environment if possible. Or start fresh with a fresh Ubuntu install. One thing to test would be to try the vagrant development environment that we have in the source tree here.

**Comment by pearlymaccha** [comment]
Ok I'll try the vagrant development environment. Thank you for your suggest @michaelshobbs
